### ISSUE TITLE
Customer Country information is not being passed

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/ccavenue-plugin-for-nopcommerce#1]
While using CCAvenue, the customer country information is not working and the payment site shows it as unselected.

Related issue reports here as well
http://www.nopcommerce.com/boards/t/9275/ccavenue-not-sending-country-info.aspx

**Comment by skoshelev** [comment]
@sukeshak Could you please specify what version of nopCommerce are you using? And what's the plugin as well?

**Comment by sukeshak** [comment]
Right now I am on nopCommerce 3.7, the issue is happening.
In few months will be moving to 3.8, once some of the plugins I use add support for 3.8.

**Comment by skoshelev** [comment]
@sukeshak  Our CCAvenue credentials that we used for testing are outdated already. Do you have an opportunity to provide (email) your testing (sandbox) credentials so we can test it or fix as soon as possible?

**Comment by sukeshak** [comment]
@skoshelev I don't have test credentials. What I have is live one.
Let me check with them for help... if not atleast get test credentials for you.

**Comment by sukeshak** [comment]
@skoshelev 

Looks like in code we are sending ThreeLetterIsoCode  but as per documentation its expecting 50 chars (so guessing it should be the full name of the country). See the attached screenshot

var billingCountry = postProcessPaymentRequest.Order.BillingAddress.Country;
remotePostHelperData.Add("billing_country", billingCountry != null ? billingCountry.ThreeLetterIsoCode : string.Empty);

From API Doc on their website:
billing_country
Customer's billing country
Alphabets (50)

Characters allowed:
Alphabet (A-Z), (a-z).
Space in between words.

I don't currently have a dev setup for changing code and build for testing.
If you can give a plugin build with the above changes, I can test it though.

The same applies to both billing_country & delivery_country

<img width="331" alt="ccavenue-issue" src="https://cloud.githubusercontent.com/assets/9167668/18419475/5846794a-7879-11e6-9569-fb97d1eaeb46.png">

**Comment by skoshelev** [comment]
@sukeshak Thank you for the suggestion. I compiled the necessary changes for two versions, if it's possible please check both.

[CCAvenue_3.80.zip](https://github.com/nopSolutions/ccavenue-plugin-for-nopcommerce/files/466741/CCAvenue_3.80.zip)
[CCAvenue_3.70.zip](https://github.com/nopSolutions/ccavenue-plugin-for-nopcommerce/files/466740/CCAvenue_3.70.zip)

**Comment by sukeshak** [comment]
Will test and revert today

**Comment by sukeshak** [comment]
Tested with 3.7 version which is in pre-production and it did not work :(
Will be migrating to 3.8 by end of this week and can test by then but does not look like the real solution.

Will check with CCAvenue support as well and get back.

**Comment by sukeshak** [comment]
When I cancelled the transaction it showed the data which were submitted and I see this result for country field

billing_country = IND
delivery_country = India

Did you make the change for billing_country as well (still shows 3 letter) ? 
Guess you changed only for delivery_country in this test build?

I have also sent support request to CCAvenue, will wait to hear from them too.

**Comment by sukeshak** [comment]
Guess I was right. Billing country is still not updated in your test build you gave.

remotePostHelperData.Add("billing_country", billingCountry.get_ThreeLetterIsoCode());

**Comment by skoshelev** [comment]
@sukeshak Thank you. Please try this version of the plugin (for 3.70)
[Payments.CCAvenue.zip](https://github.com/nopSolutions/ccavenue-plugin-for-nopcommerce/files/469024/Payments.CCAvenue.zip)

**Comment by sukeshak** [comment]
Can you provide 3.8 version too...
I upgraded my site to 3.8 yesterday night :)

**Comment by skoshelev** [comment]
@sukeshak Of course.
[(3.80)Payments.CCAvenue.zip](https://github.com/nopSolutions/ccavenue-plugin-for-nopcommerce/files/469347/3.80.Payments.CCAvenue.zip)

**Comment by sukeshak** [comment]
Ok tested on 3.8 and it works 👍

**Comment by sukeshak** [comment]
If I cancel out from transaction page to get back to the website, it takes to this URL
http://mydomainname/Plugins/PaymentCCAvenue/Return

and shows the submitted content and the following at the end.
response_code = Security Error. Illegal access detected

Is this expected?

**Comment by skoshelev** [comment]
@sukeshak Сan you specify the entire path with parameters from /Return?

**Comment by sukeshak** [comment]
Other parameters are all related to the data submitted related to my website, which I cannot quote here.

**Comment by skoshelev** [comment]
@sukeshak Ok. I need order_status parameter's value, are you have it?

**Comment by sukeshak** [comment]
I will get that and revert soon
