### ISSUE TITLE
Order confirmed / inventory deducted even if payment failed

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/ccavenue-plugin-for-nopcommerce#2]
The workflow of this plugin is not correct.
- The payment page redirection happens after the order is confirmed
- If payment fails, the inventory is still getting deducted which is causing issues for us.

What is expected:
Inventory changes should happen only if order is confirmed and payment status is Paid.

**Comment by AndreiMaz** [comment]
no, it's by design in nopCommerce (when placing an order)

**Comment by sukeshak** [comment]
After reading all the discussions on forum, I think this is a big issue for all of us and need some attention to help us get this behavior changed. For lower stock products, going out of stock is a major issue just because someone clicked through till Confirm button.

If there is a workaround which can be implemented... probably its a good idea for people who need this corrected.
