### ISSUE TITLE
Not able to install CCAvenue plugin 

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/ccavenue-plugin-for-nopcommerce#4]
nopCommerce version:
4.20
Steps to reproduce the problem:
Download CCAvenue plugin from below location
http://downloads.nopcommerce.com/Extensions/UserContributions/58046_1030_CCAvenue.zip
Go to
/Admin/Plugin/Plugins
and upload plugin
It says
" 0 plugins and 0 themes have been uploaded"

**Comment by AndreiMaz** [comment]
4.20 is not released yet. Hence it's not supported
