### ISSUE TITLE
failed to load resource: .net::err_http2_protocol_error

### ISSUE THREAD

**Issue by saravananmuthiah** [nopSolutions/ccavenue-plugin-for-nopcommerce#8]
When run this plugin on my local machine or Windows 2022 datacenter, i get "failed to load resource: .net::err_http2_protocol_error"

What is this mean how to fix it?
![KB5003637  issue](https://user-images.githubusercontent.com/32478577/155138904-4a21175c-e4e8-4758-996f-eb7e06244193.png)

**Comment by rajupaladiya** [comment]
Is this resolved?

**Comment by skoshelev** [comment]
Unfortunately, it was not possible to reproduce the problem locally, it looks like some kind of problem with resource availability on a specific server

Closed #8
