### ISSUE TITLE
Verify payment confirmation using either a WebHook or a scheduled task, if failed due to internet issue

### ISSUE THREAD

**Issue by sameerdube9** [nopSolutions/ccavenue-plugin-for-nopcommerce#9]
There is a scenario in which a payment is successfully made on the CCAvenue website, but due to an internet issue, the website does not receive confirmation from the CCAvenue website.

Is it possible to address this issue by utilizing a Webhook if it's provided by the CCAvenue website?

Alternatively,

Can we implement a scheduled task that checks the status of an order for payment confirmation and marks it as 'Paid' if it's found to be true, within 30 minutes of the order being placed?

**Comment by AndreiMaz** [comment]
@samdubey Thanks a lot for suggestion. But it's a quite rare event. So we're leaving it for customization. Anyway, a store owner can always manually mark an order as paid
